FROM ubuntu:16.04
MAINTAINER jhonny <jonthdiaz@gmail.com>
#update reports
RUN apt-get update

RUN apt-get install -qy vim \
                        wget \
                        net-tools \
                        git \
                        curl \
                        zsh \
                        git-core \
                        libpq-dev \
                        python \
                        python3.4 \
                        python-dev \
                        python3-dev \
                        python-pip \
                        python-setuptools \
                        build-essential \
                        python3-pip \
                        libcurl4-openssl-dev \
                        libffi-dev \
                        libjpeg-dev

# RUN apt-get install language-pack-en-base -y && sudo locale-gen es_CO es_CO.UTF-8 && sudo dpkg-reconfigure locales
